//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/ArcadeControllerTest/Scripts/Play.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/ArcadeControllerTest/Scripts/Play.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
namespace ArcadeControllerTest.Inputs
{
    
    public partial class @Play: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }
    
        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @Play()
        {
            asset = InputActionAsset.FromJson(@"{
        ""version"": 1,
        ""name"": ""Play"",
        ""maps"": [
            {
                ""name"": ""Type1"",
                ""id"": ""a1420030-6262-4706-864a-aa5d1bb862aa"",
                ""actions"": [
                    {
                        ""name"": ""1"",
                        ""type"": ""Button"",
                        ""id"": ""99c20761-ea9f-460b-be8b-88fb7c109e43"",
                        ""expectedControlType"": """",
                        ""processors"": """",
                        ""interactions"": """",
                        ""initialStateCheck"": false
                    },
                    {
                        ""name"": ""2"",
                        ""type"": ""Button"",
                        ""id"": ""a167d496-4825-460f-b37f-84e0413e4e32"",
                        ""expectedControlType"": """",
                        ""processors"": """",
                        ""interactions"": """",
                        ""initialStateCheck"": false
                    },
                    {
                        ""name"": ""3"",
                        ""type"": ""Button"",
                        ""id"": ""81586e8c-4a08-4be2-b4a5-4b170da5c192"",
                        ""expectedControlType"": """",
                        ""processors"": """",
                        ""interactions"": """",
                        ""initialStateCheck"": false
                    },
                    {
                        ""name"": ""4"",
                        ""type"": ""Button"",
                        ""id"": ""c0823eff-564f-401f-abbc-17bcf7d498c3"",
                        ""expectedControlType"": """",
                        ""processors"": """",
                        ""interactions"": """",
                        ""initialStateCheck"": false
                    }
                ],
                ""bindings"": [
                    {
                        ""name"": """",
                        ""id"": ""92048242-3d4a-4f65-a781-b231eb2068f0"",
                        ""path"": ""<HID::WiseGroup.,Ltd JC-AS01 series>/button3"",
                        ""interactions"": """",
                        ""processors"": """",
                        ""groups"": """",
                        ""action"": ""1"",
                        ""isComposite"": false,
                        ""isPartOfComposite"": false
                    },
                    {
                        ""name"": """",
                        ""id"": ""fd446857-51f4-4fcd-b102-a5430fe0b74d"",
                        ""path"": ""<HID::WiseGroup.,Ltd JC-AS01 series>/button2"",
                        ""interactions"": """",
                        ""processors"": """",
                        ""groups"": """",
                        ""action"": ""2"",
                        ""isComposite"": false,
                        ""isPartOfComposite"": false
                    },
                    {
                        ""name"": """",
                        ""id"": ""dcee53c4-6cc3-4fb2-856f-d8f84c8ce431"",
                        ""path"": ""<HID::WiseGroup.,Ltd JC-AS01 series>/button6"",
                        ""interactions"": """",
                        ""processors"": """",
                        ""groups"": """",
                        ""action"": ""3"",
                        ""isComposite"": false,
                        ""isPartOfComposite"": false
                    },
                    {
                        ""name"": """",
                        ""id"": ""63a8ca40-a77b-4dd9-aeb6-a1ef7650b0f1"",
                        ""path"": ""<HID::WiseGroup.,Ltd JC-AS01 series>/button5"",
                        ""interactions"": """",
                        ""processors"": """",
                        ""groups"": """",
                        ""action"": ""4"",
                        ""isComposite"": false,
                        ""isPartOfComposite"": false
                    }
                ]
            }
        ],
        ""controlSchemes"": []
    }");
            // Type1
            m_Type1 = asset.FindActionMap("Type1", throwIfNotFound: true);
            m_Type1__1 = m_Type1.FindAction("1", throwIfNotFound: true);
            m_Type1__2 = m_Type1.FindAction("2", throwIfNotFound: true);
            m_Type1__3 = m_Type1.FindAction("3", throwIfNotFound: true);
            m_Type1__4 = m_Type1.FindAction("4", throwIfNotFound: true);
        }
    
        ~@Play()
        {
            UnityEngine.Debug.Assert(!m_Type1.enabled, "This will cause a leak and performance issues, Play.Type1.Disable() has not been called.");
        }
    
        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }
    
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }
    
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }
    
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;
    
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }
    
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }
    
        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }
    
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }
    
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;
    
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
    
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }
    
        // Type1
        private readonly InputActionMap m_Type1;
        private List<IType1Actions> m_Type1ActionsCallbackInterfaces = new List<IType1Actions>();
        private readonly InputAction m_Type1__1;
        private readonly InputAction m_Type1__2;
        private readonly InputAction m_Type1__3;
        private readonly InputAction m_Type1__4;
        /// <summary>
        /// Provides access to input actions defined in input action map "Type1".
        /// </summary>
        public struct Type1Actions
        {
            private @Play m_Wrapper;
    
            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public Type1Actions(@Play wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Type1/_1".
            /// </summary>
            public InputAction @_1 => m_Wrapper.m_Type1__1;
            /// <summary>
            /// Provides access to the underlying input action "Type1/_2".
            /// </summary>
            public InputAction @_2 => m_Wrapper.m_Type1__2;
            /// <summary>
            /// Provides access to the underlying input action "Type1/_3".
            /// </summary>
            public InputAction @_3 => m_Wrapper.m_Type1__3;
            /// <summary>
            /// Provides access to the underlying input action "Type1/_4".
            /// </summary>
            public InputAction @_4 => m_Wrapper.m_Type1__4;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Type1; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="Type1Actions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(Type1Actions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="Type1Actions" />
            public void AddCallbacks(IType1Actions instance)
            {
                if (instance == null || m_Wrapper.m_Type1ActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_Type1ActionsCallbackInterfaces.Add(instance);
                @_1.started += instance.On_1;
                @_1.performed += instance.On_1;
                @_1.canceled += instance.On_1;
                @_2.started += instance.On_2;
                @_2.performed += instance.On_2;
                @_2.canceled += instance.On_2;
                @_3.started += instance.On_3;
                @_3.performed += instance.On_3;
                @_3.canceled += instance.On_3;
                @_4.started += instance.On_4;
                @_4.performed += instance.On_4;
                @_4.canceled += instance.On_4;
            }
    
            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="Type1Actions" />
            private void UnregisterCallbacks(IType1Actions instance)
            {
                @_1.started -= instance.On_1;
                @_1.performed -= instance.On_1;
                @_1.canceled -= instance.On_1;
                @_2.started -= instance.On_2;
                @_2.performed -= instance.On_2;
                @_2.canceled -= instance.On_2;
                @_3.started -= instance.On_3;
                @_3.performed -= instance.On_3;
                @_3.canceled -= instance.On_3;
                @_4.started -= instance.On_4;
                @_4.performed -= instance.On_4;
                @_4.canceled -= instance.On_4;
            }
    
            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Type1Actions.UnregisterCallbacks(IType1Actions)" />.
            /// </summary>
            /// <seealso cref="Type1Actions.UnregisterCallbacks(IType1Actions)" />
            public void RemoveCallbacks(IType1Actions instance)
            {
                if (m_Wrapper.m_Type1ActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }
    
            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="Type1Actions.AddCallbacks(IType1Actions)" />
            /// <seealso cref="Type1Actions.RemoveCallbacks(IType1Actions)" />
            /// <seealso cref="Type1Actions.UnregisterCallbacks(IType1Actions)" />
            public void SetCallbacks(IType1Actions instance)
            {
                foreach (var item in m_Wrapper.m_Type1ActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_Type1ActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="Type1Actions" /> instance referencing this action map.
        /// </summary>
        public Type1Actions @Type1 => new Type1Actions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Type1" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="Type1Actions.AddCallbacks(IType1Actions)" />
        /// <seealso cref="Type1Actions.RemoveCallbacks(IType1Actions)" />
        public interface IType1Actions
        {
            /// <summary>
            /// Method invoked when associated input action "1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void On_1(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void On_2(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void On_3(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void On_4(InputAction.CallbackContext context);
        }
    }
}
